models:
  Random Forest:
    n_estimators: 100
    max_depth: 10
    random_state: 42
  Decision Tree:
    max_depth: 10
    random_state: 42
  Gradient Boosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 5
    random_state: 42
  Linear Regression: {}
  CatBoosting Regressor:
    iterations: 1000
    learning_rate: 0.1
    depth: 6
    random_seed: 42
  AdaBoost Regressor:
    n_estimators: 100
    learning_rate: 0.1
    random_state: 42
  KNeighbors Regressor:
    n_neighbors: 5
    weights: uniform
    algorithm: auto
